version: "2.4"
services:
  app-springboot:
    build:
      context: ./springboot
      dockerfile: ./Dockerfile
    image: springboot-app:latest
    ports:
      - "8081:8080"
    mem_limit: 4096m
    cpus: 4.0
  app-vertx:
    build:
      context: ./vertx
      dockerfile: ./Dockerfile
    image: vertx-app:latest
    ports:
      - "8082:8080"
    mem_limit: 4096m
    cpus: 4.0